name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Heroku
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: |
        # Ensure git remote is clean
        git remote remove heroku || true
        
        # Add Heroku remote
        git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/poker-tele-bot.git
        
        # Force push to Heroku
        git push -f heroku main
